CREATE TABLE srbp_stage.FUND_CASH_STAGE(
FUND_CASH_ACCT_SEQ				STRING,
INVST_PLAN_ARR_SEQ				STRING,
ACCT_CASH_FUND					STRING,
ACCT_CASH_FUND_TYPE_CDE			STRING,
CCY_ACCT_CASH_FUND_CDE			STRING,
LAST_INGESTION_TIMESTAMP		TIMESTAMP,
PRM_LNE_OF_BUS_CDE_FILTER		STRING,
CTRY_CDE_FILTER					STRING,
ENTITY_CDE_FILTER				STRING)

******************************************************************

CREATE TABLE srbp_stage.GHSS_ACCT_STAGE(
ACCT_INVST_NUM				STRING,
GRP_MEMBER_CDE				STRING,
CTRY_CDE					STRING,
CE_INCM_CASH_ACCT_TYPE		STRING,
CE_INCM_CASH_ACCT_CCY_CDE	STRING,
CE_INCM_CASH_ACCT			STRING,
LAST_INGESTION_TIMESTAMP	TIMESTAMP,
PRM_LNE_OF_BUS_CDE_FILTER	STRING,
CTRY_CDE_FILTER				STRING,
ENTITY_CDE_FILTER			STRING)


*******************************************************************

CREATE TABLE srbp_stage.INVST_PLAN_STAGE(
INVST_PLAN_ARR_SEQ_NUM		STRING,
SEQ_DISP_NUM				STRING,
CTRY_INVST_ACCT_CDE			STRING,
GRP_MEMBR_INVST_ACCT_CDE	STRING,
ACCT_INVST_NUM				STRING,
ENGMT_STYLE_CDE				STRING,
INVST_PLAN_NUM				STRING,
INVST_PLAN_STAT_CDE			STRING,
PDCY_INVST_CDE				STRING,
PLAN_INSTR_NEXT_TM			TIMESTAMP,
PLAN_INSTR_NEXT_DT			DATE,
CCY_INVST_REG_CDE			STRING,
INVST_REG_AMT				STRING,
CCY_INVST_ACCUM_CDE			STRING,
INVST_ACCUM_AMT				STRING,
CNTRB_SUCS_TTL_CNT			STRING,
CNTRB_LAST_DT_TM			TIMESTAMP,
MDUN_SYS_CDE				STRING,
LAST_INGESTION_TIMESTAMP	TIMESTAMP,
PRM_LNE_OF_BUS_CDE_FILTER	STRING,
CTRY_CDE_FILTER				STRING,
ENTITY_CDE_FILTER			STRING)

******************************************************
CREATE TABLE srbp_stage.INVST_PLAN_PROD_STAGE(
INVS_PLN_ARR_PRD_SEQ_NUM	STRING,
INVST_PLAN_ARR_SEQ_NUM		STRING,
PROD_ALT_NUM				STRING,
PROD_CDE_ALT_CLASS_CDE		STRING,
CTRY_PROD_TRADE_CDE			STRING,
ASET_CLASS_CDE				STRING,
LAST_INGESTION_TIMESTAMP	TIMESTAMP,
PRM_LNE_OF_BUS_CDE_FILTER	STRING,
CTRY_CDE_FILTER				STRING,
ENTITY_CDE_FILTER			STRING)

**********************************************************

CREATE TABLE srbp_stage.MIG_UINVST_ACCT_STAGE(
ACCT_EXTNL_NUM				STRING,
SYS_EXTNL_CDE				STRING,
CTRY_INVST_ACCT_CDE			STRING,
GRP_MEMBR_INVST_ACCT_CDE	STRING,
SRCE_SYS_NAME				STRING,
ACCT_MIG_FUND_IND			STRING,
LAST_INGESTION_TIMESTAMP	TIMESTAMP,
PRM_LNE_OF_BUS_CDE_FILTER	STRING,
CTRY_CDE_FILTER				STRING,
ENTITY_CDE_FILTER			STRING)




